name: Auto Commit and Push

on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commit and push changes
        run: |
          git config user.name "Your Name"
          git config user.email "your.email@example.com"
          git add .
          git commit -m "Automated commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
