#!/bin/bash
echo "=== ANALYZING PAGELAYOUT BANNER ==="
echo ""

FILE="src/components/PageLayout.jsx"

echo "Current banner in PageLayout (lines around the banner section):"
# Find the banner section
grep -n "position: \"fixed\", top: \"45px\"" "$FILE"
LINE=$(grep -n "position: \"fixed\", top: \"45px\"" "$FILE" | cut -d: -f1)
echo "Banner starts at line: $LINE"
echo ""
echo "Banner content:"
sed -n "${LINE},$((LINE+40))p" "$FILE"
echo ""
echo "=== CURRENT STRUCTURE ==="
echo "1. Two side boxes"
echo "2. ONE center logo"
echo "3. Company name below"
echo "4. Tagline below that"
echo "5. AI tagline at bottom"
echo ""
echo "=== DESIRED STRUCTURE ==="
echo "1. Logo on LEFT side"
echo "2. Left side box"
echo "3. Company name in center (moved down from border)"
echo "4. Right side box"
echo "5. Logo on RIGHT side"
echo "6. Sovereign Health tagline"
echo "7. Star pattern background"
echo "8. Page title (YOU ARE HOME)"
