#!/bin/bash
echo "=== BYPASSING BROWSER CACHE ==="
echo ""
echo "1. Test with unique URL to bypass cache:"
echo "   http://localhost:3000/images/MAVJLogo.jpg?t=12345"
echo ""
echo "2. Or open browser in Incognito/Private mode"
echo ""
echo "3. Or force refresh:"
echo "   Chrome: Ctrl+Shift+R or Cmd+Shift+R"
echo "   Firefox: Ctrl+F5 or Cmd+Shift+R"
echo ""
echo "4. Check browser Developer Tools:"
echo "   - Network tab: See if request is made"
echo "   - Console tab: Any errors"
echo "   - Application tab: Clear storage"
echo ""
echo "5. Try different browser"
echo "   Firefox, Safari, Edge"
