#!/bin/bash
echo "=== QUICK TEST ==="
echo ""
echo "1. Fix applied: /frontend/public/images/ → /images/"
echo ""
echo "2. Start server:"
echo "   npm start"
echo ""
echo "3. Test: http://localhost:3000/images/MAVJLogo.jpg"
echo "   ✓ Shows logo: Path is correct"
echo "   ✗ 404 error: Logo not in public/images/"
echo ""
echo "4. Then test main page: http://localhost:3000"
echo ""
echo "The path was wrong. It's fixed now."
