#!/bin/bash
echo "=== TESTING WITH CURL ==="
echo ""
echo "1. Start server in one terminal: npm start"
echo ""
echo "2. In another terminal, run:"
echo "   curl -v http://localhost:3000/images/MAVJLogo.jpg"
echo ""
echo "3. Look for:"
echo "   ✓ HTTP/1.1 200 OK - File served"
echo "   ✗ HTTP/1.1 404 Not Found - File not found"
echo "   ✗ HTTP/1.1 403 Forbidden - Permission issue"
echo ""
echo "4. Also check file permissions:"
echo "   ls -la public/images/MAVJLogo.jpg"
echo "   Should be readable: -rw-r--r--"
echo ""
echo "Let me check permissions now:"
ls -la public/images/MAVJLogo.jpg 2>/dev/null || echo "File not found"
