#!/bin/bash

FILE="HomePage.js"

echo "=== EXACT FIX FOR CONTAINER 2 ==="
echo "Working on: $FILE"

# First, let's find the exact line numbers
TITLE_SECTION_START=1601  # From your grep output
CONTAINER2_JSX_START=2502 # From your grep output
ANNOUNCEMENTS_JSX_START=2553 # From your grep output

echo "Found:"
echo "- titleSection styles start at line: $TITLE_SECTION_START"
echo "- Container 2 JSX starts at line: $CONTAINER2_JSX_START"
echo "- ANNOUNCEMENTS JSX at line: $ANNOUNCEMENTS_JSX_START"

# Create a temporary file for the new version
TEMP_FILE=$(mktemp)

# 1. First replace the styles (lines 1601 and following)
echo "Replacing titleSection styles..."
awk '
BEGIN { in_title_section = 0; replaced = 0 }
NR == 1601 {
    in_title_section = 1
    print "    // CONTAINER 2: WEBSITE BANNER (STICKY ON ALL PAGES)"
    print "    titleSection: {"
    print "      position: \"fixed\","
    print "      top: \"88px\", // 35px (disclaimer) + 45px (navbar) + 8px gap"
    print "      left: 0,"
    print "      right: 0,"
    print "      zIndex: 1700,"
    print "      backgroundImage: \"url(/images/star-pattern.png)\","
    print "      backgroundSize: \"100px\","
    print "      backgroundPosition: \"center\","
    print "      backgroundColor: \"rgba(0, 0, 0, 0.96)\","
    print "      backgroundBlendMode: \"overlay\","
    print "      border: \"3px solid\", // FOUR-SIDED RAINBOW BORDER"
    print "      borderImage: \"linear-gradient(90deg, violet, indigo, blue, green, yellow, orange, red) 1\","
    print "      padding: \"15px 20px 12px\","
    print "      display: \"flex\","
    print "      flexDirection: \"column\","
    print "      alignItems: \"center\","
    print "      justifyContent: \"center\","
    print "      backdropFilter: \"blur(8px)\","
    print "      boxShadow: \"0 4px 25px rgba(0,0,0,0.9)\","
    print "      minHeight: \"200px\","
    print "      maxHeight: \"200px\""
    print "    },"
    print ""
    print "    // ROW 1: LARGE COMPANY NAME"
    print "    companyName: {"
    print "      fontSize: \"clamp(2rem, 5vw, 2.8rem)\","
    print "      fontWeight: \"900\","
    print "      color: \"#FFD700\","
    print "      textAlign: \"center\","
    print "      margin: \"0 0 10px\","
    print "      letterSpacing: \"2.5px\","
    print "      textShadow: \"0 0 25px rgba(255,215,0,0.95)\","
    print "      lineHeight: \"1.1\","
    print "      whiteSpace: \"nowrap\""
    print "    },"
    print ""
    print "    // ROW 2: LOGO ROW - BOXES AT EXTREMES"
    print "    logoRow: {"
    print "      display: \"flex\","
    print "      alignItems: \"center\","
    print "      justifyContent: \"space-between\","
    print "      width: \"100%\","
    print "      margin: \"5px 0 10px\","
    print "      padding: \"0 10px\""
    print "    },"
    print ""
    print "    // SIDE BOX WRAPPER - COMPACT AT EXTREMES"
    print "    sideBoxWrapper: {"
    print "      background: \"linear-gradient(135deg, violet, indigo, blue, green, yellow, orange, red)\","
    print "      borderRadius: \"6px\","
    print "      padding: \"2px\","
    print "      display: \"flex\","
    print "      alignItems: \"center\","
    print "      justifyContent: \"center\","
    print "      flexShrink: 0,"
    print "      width: \"20%\","
    print "      minWidth: \"150px\","
    print "      maxWidth: \"180px\""
    print "    },"
    print ""
    print "    // SIDE BOX INNER - TIGHT, NO EXTRA SPACE"
    print "    sideBoxInner: {"
    print "      background: \"rgba(0, 0, 0, 0.96)\","
    print "      borderRadius: \"4px\","
    print "      padding: \"8px 10px\","
    print "      fontSize: \"0.75rem\","
    print "      fontWeight: \"800\","
    print "      color: \"#FFD700\","
    print "      lineHeight: \"1.2\","
    print "      textAlign: \"center\","
    print "      whiteSpace: \"nowrap\","
    print "      display: \"flex\","
    print "      flexDirection: \"column\","
    print "      justifyContent: \"center\","
    print "      gap: \"3px\","
    print "      width: \"100%\""
    print "    },"
    print ""
    print "    // LOGO CIRCLE - LARGER USING EXTRA SPACE"
    print "    logoCircle: {"
    print "      width: \"80px\","
    print "      height: \"80px\","
    print "      borderRadius: \"50%\","
    print "      border: \"3px solid #FFD700\","
    print "      overflow: \"hidden\","
    print "      background: \"#fff\","
    print "      boxShadow: \"0 0 30px rgba(255,215,0,0.9)\","
    print "      animation: \"heartbeat 1.4s ease-in-out infinite\","
    print "      flexShrink: 0"
    print "    },"
    print ""
    print "    logoImg: {"
    print "      width: \"100%\","
    print "      height: \"100%\","
    print "      objectFit: \"contain\","
    print "      padding: \"6px\""
    print "    },"
    print ""
    print "    // ROW 3: PAGE TITLE"
    print "    pageTitle: {"
    print "      fontSize: \"clamp(1.2rem, 2.5vw, 1.5rem)\","
    print "      fontWeight: \"900\","
    print "      color: \"#00d4ff\","
    print "      textAlign: \"center\","
    print "      margin: \"5px 0 8px\","
    print "      letterSpacing: \"3px\","
    print "      textTransform: \"uppercase\","
    print "      textShadow: \"0 0 12px rgba(0,212,255,0.7)\","
    print "      whiteSpace: \"nowrap\""
    print "    },"
    print ""
    print "    // ROW 4: TAGLINE ROW"
    print "    taglineRow: {"
    print "      display: \"flex\","
    print "      justifyContent: \"center\","
    print "      alignItems: \"center\","
    print "      gap: \"12px\","
    print "      margin: \"5px 0\","
    print "      fontSize: \"0.85rem\","
    print "      fontWeight: \"800\","
    print "      flexWrap: \"wrap\""
    print "    },"
    print ""
    print "    taglineItemRed: {"
    print "      color: \"#FF0000\","
    print "      whiteSpace: \"nowrap\","
    print "      textShadow: \"0 0 8px rgba(255,0,0,0.5)\""
    print "    },"
    print ""
    print "    taglineItemGreen: {"
    print "      color: \"#00FF00\","
    print "      whiteSpace: \"nowrap\","
    print "      textShadow: \"0 0 8px rgba(0,255,0,0.5)\""
    print "    },"
    print ""
    print "    taglineItemBlue: {"
    print "      color: \"#0000FF\","
    print "      whiteSpace: \"nowrap\","
    print "      textShadow: \"0 0 8px rgba(0,0,255,0.5)\""
    print "    },"
    print ""
    print "    separator: {"
    print "      color: \"#FFD700\","
    print "      margin: \"0 3px\","
    print "      fontWeight: \"900\""
    print "    },"
    print ""
    print "    // ROW 5: AI DECLARATION"
    print "    aiDeclaration: {"
    print "      fontSize: \"0.9rem\","
    print "      fontWeight: \"900\","
    print "      color: \"#FFD700\","
    print "      textAlign: \"center\","
    print "      margin: \"8px 0 0\","
    print "      textShadow: \"0 0 10px rgba(255,215,0,0.8)\","
    print "      whiteSpace: \"nowrap\","
    print "      letterSpacing: \"1px\""
    print "    },"
    print ""
    replaced = 1
    next
}
in_title_section && /^    [a-zA-Z]/ && !/^    titleSection/ && !replaced {
    in_title_section = 0
}
!in_title_section { print }
' "$FILE" > "$TEMP_FILE"

mv "$TEMP_FILE" "$FILE"
echo "✅ Styles replaced"

# 2. Now replace the JSX (lines 2502 to 2552)
echo "Replacing Container 2 JSX..."
TEMP_FILE2=$(mktemp)

awk '
BEGIN { in_container2_jsx = 0; replaced_jsx = 0 }
NR == 2502 {
    in_container2_jsx = 1
    print "      {/* CONTAINER 2: WEBSITE BANNER (STICKY ON ALL PAGES) */}"
    print "      <section style={styles.titleSection}>"
    print ""
    print "        {/* ROW 1: LARGE COMPANY NAME */}"
    print "        <h1 style={styles.companyName}>"
    print "          💦 MY ALKALINE VEGAN JOURNEY 💦"
    print "        </h1>"
    print ""
    print "        {/* ROW 2: LOGO WITH SIDE BOXES AT EXTREMES */}"
    print "        <div style={styles.logoRow}>"
    print ""
    print "          {/* LEFT BOX */}"
    print "          <div style={styles.sideBoxWrapper}>"
    print "            <div style={styles.sideBoxInner}>"
    print "              <div>Quantum Based</div>"
    print "              <div>Scientifically Backed</div>"
    print "              <div>Frequency Focused</div>"
    print "            </div>"
    print "          </div>"
    print ""
    print "          {/* CENTER LOGO - LARGER */}"
    print "          <div style={styles.logoCircle}>"
    print "            <img"
    print "              src=\"/images/MAVJLogo.jpg\""
    print "              alt=\"MAVJ Logo\""
    print "              style={styles.logoImg}"
    print "              onError={(e) => { e.target.onerror = null; e.target.src = \"/images/star-pattern.png\"; }}"
    print "            />"
    print "          </div>"
    print ""
    print "          {/* RIGHT BOX */}"
    print "          <div style={styles.sideBoxWrapper}>"
    print "            <div style={styles.sideBoxInner}>"
    print "              <div>Where Quantum Physics</div>"
    print "              <div>Meets Ancient Wisdom</div>"
    print "              <div>And Nutrition</div>"
    print "            </div>"
    print "          </div>"
    print "        </div>"
    print ""
    print "        {/* ROW 3: PAGE TITLE */}"
    print "        <div style={styles.pageTitle}>"
    print "          YOU ARE HOME"
    print "        </div>"
    print ""
    print "        {/* ROW 4: TAGLINE */}"
    print "        <div style={styles.taglineRow}>"
    print "          <span style={styles.taglineItemRed}>Sovereign Living</span>"
    print "          <span style={styles.separator}>—</span>"
    print "          <span style={styles.taglineItemGreen}>Frequency Transformation</span>"
    print "          <span style={styles.separator}>—</span>"
    print "          <span style={styles.taglineItemBlue}>Ancestral Nutrition</span>"
    print "        </div>"
    print ""
    print "        {/* ROW 5: AI DECLARATION */}"
    print "        <div style={styles.aiDeclaration}>"
    print "          🤖 AI-POWERED QUANTUM ENTERPRISE 🤖"
    print "        </div>"
    print ""
    print "      </section>"
    print ""
    replaced_jsx = 1
    next
}
NR == 2553 {
    if (replaced_jsx) {
        in_container2_jsx = 0
        print "      {/* ANNOUNCEMENTS (Conditional) */}"
        next
    }
}
!in_container2_jsx { print }
' "$FILE" > "$TEMP_FILE2"

mv "$TEMP_FILE2" "$FILE"
echo "✅ JSX replaced"

# 3. Update paddingTop
echo "Updating paddingTop..."
sed -i "s/paddingTop: '220px' // Space for fixed headers - REDUCED FROM 280px/paddingTop: '300px' \/\/ Space for fixed banner (disclaimer + navbar + banner)/" "$FILE"

# 4. Add heartbeat animation if not exists
if ! grep -q "@keyframes heartbeat" "$FILE"; then
    echo "Adding heartbeat animation..."
    sed -i '/@keyframes logoPulse {/,/^[[:space:]]*}/ {
        /^[[:space:]]*}/a\
        @keyframes heartbeat {\
          0%, 100% { transform: scale(1); box-shadow: 0 0 16px rgba(255,215,0,0.85); }\
          14% { transform: scale(1.13); box-shadow: 0 0 24px rgba(255,215,0,1); }\
          28% { transform: scale(1); box-shadow: 0 0 16px rgba(255,215,0,0.85); }\
          42% { transform: scale(1.09); box-shadow: 0 0 22px rgba(255,215,0,0.95); }\
          70% { transform: scale(1); box-shadow: 0 0 16px rgba(255,215,0,0.85); }\
        }
    }' "$FILE"
fi

echo ""
echo "🎉 CONTAINER 2 COMPLETELY FIXED!"
echo ""
echo "Check that these changes were made:"
echo "1. ✅ New titleSection styles at line 1601"
echo "2. ✅ New Container 2 JSX at line 2502"
echo "3. ✅ paddingTop updated to 300px"
echo "4. ✅ heartbeat animation added"
echo ""
echo "The banner should now show:"
echo "- Large company name at top"
echo "- Side boxes at far left/right"
echo "- Large 80px logo in center"
echo "- Page title: YOU ARE HOME"
echo "- Tagline: Sovereign Living — Frequency Transformation — Ancestral Nutrition"
echo "- AI: 🤖 AI-POWERED QUANTUM ENTERPRISE ��"
echo "- Four-sided rainbow border"
echo "- Star pattern background"
echo "- Positioned at 88px (below menu)"
